---
- name: Installing PTS Dependencies
  become: True
  apt:
    name:
    - bc
    - git
    - php-cli
    - php-xml
    - php-zip
    - php-json
    - php-mbstring
    - php-gd
    - unzip
    - make
    - gcc
    - perl
    - build-essential
    - autoconf
    - libopenmpi-dev
    - openmpi-bin
    - libmpich-dev
    - libblas-dev
    - libopenblas-openmp-dev
    - libatlas-base-dev
    - liblapack-dev
    - liblapacke-dev
    - mesa-utils
    - vulkan-tools
    - unzip
    - apt-file
    state: present

- name: Downloading Phoronix Test Suite
  shell: wget https://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_10.8.4_all.deb --no-check-certificate

- name: Installing Phoronix Test Suite
  shell: dpkg -i phoronix-test-suite_10.8.4_all.deb

- name: Verifying the Test Suite Installation
  shell: phoronix-test-suite version

- name: Installing HPL Linpack Benchmark
  become: True
  command: phoronix-test-suite install hpl
  args:
    executable: /bin/bash

- name: Copy batch-run file to target host
  copy:
    src: templates/user-config.xml.j2
    dest: . user-config.xml
  become: True

# - name: Generate a dynamic name for HPL results
#   set_fact:
#     hpl_results_name: "{{ ansible_default_ipv4.address }}{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"

- name: Run HPL Linpack Benchmark with dynamic name
  command: sudo phoronix-test-suite batch-run hpl
  become: True
  args:
    executable: /bin/bash
    user_configs:
    - user: urvish
      config:
        BatchMode:
          SaveResults: true

- name: Copy test results from target host
  synchronize:
    src: /var/lib/phoronix-test-suite/test-results/
    dest: /path/on/host/test-results/  # Replace with the destination path on the host where Ansible is running
    mode: pull
  become: True